import { useGetSavingsSummary } from "@workspace/api-client-react";
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from "@/components/ui/card";
import { BarChart, Bar, XAxis, YAxis, Tooltip, ResponsiveContainer, CartesianGrid, Legend } from "recharts";
import { formatCurrency } from "@/lib/utils";
import { PiggyBank, ShieldCheck, Clock, TrendingUp, Sparkles } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Savings() {
  const { data: summary, isLoading } = useGetSavingsSummary();

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-display font-bold tracking-tight text-emerald-400 flex items-center gap-2">
            <Sparkles className="h-6 w-6" /> Value Dashboard
          </h1>
          <p className="text-muted-foreground">Quantifiable ROI and savings generated by VendorIQ AI models.</p>
        </div>
        <Button variant="outline" className="border-emerald-500/30 text-emerald-400 hover:bg-emerald-500/10">
          Generate Executive Report
        </Button>
      </div>

      <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
        <Card className="bg-gradient-to-br from-emerald-500/10 to-transparent border-emerald-500/20">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium text-emerald-400">Total Savings Identified</CardTitle>
            <PiggyBank className="h-4 w-4 text-emerald-400" />
          </CardHeader>
          <CardContent>
            {isLoading ? <div className="h-8 w-24 bg-muted animate-pulse rounded" /> : (
              <>
                <div className="text-3xl font-bold font-display text-emerald-400">{formatCurrency(summary?.totalSavings || 0)}</div>
                <p className="text-xs text-muted-foreground mt-1 text-emerald-400/70">YTD cumulative</p>
              </>
            )}
          </CardContent>
        </Card>
        
        <Card className="bg-card/50 backdrop-blur border-border/10">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Fraud Prevented</CardTitle>
            <ShieldCheck className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            {isLoading ? <div className="h-8 w-24 bg-muted animate-pulse rounded" /> : (
              <div className="text-2xl font-bold font-display">{formatCurrency(summary?.fraudPrevented || 0)}</div>
            )}
          </CardContent>
        </Card>

        <Card className="bg-card/50 backdrop-blur border-border/10">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Risk Exposure Reduced</CardTitle>
            <TrendingUp className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            {isLoading ? <div className="h-8 w-24 bg-muted animate-pulse rounded" /> : (
              <div className="text-2xl font-bold font-display">{formatCurrency(summary?.riskReduction || 0)}</div>
            )}
          </CardContent>
        </Card>

        <Card className="bg-card/50 backdrop-blur border-border/10">
          <CardHeader className="flex flex-row items-center justify-between pb-2">
            <CardTitle className="text-sm font-medium">Analyst Hours Saved</CardTitle>
            <Clock className="h-4 w-4 text-muted-foreground" />
          </CardHeader>
          <CardContent>
            {isLoading ? <div className="h-8 w-24 bg-muted animate-pulse rounded" /> : (
              <div className="text-2xl font-bold font-display">{summary?.timeSaved.toLocaleString()} hrs</div>
            )}
          </CardContent>
        </Card>
      </div>

      <div className="grid gap-6 md:grid-cols-3">
        <Card className="md:col-span-2 bg-card/50 backdrop-blur border-border/10">
          <CardHeader>
            <CardTitle>Savings Trajectory</CardTitle>
            <CardDescription>Monthly breakdown of value generation</CardDescription>
          </CardHeader>
          <CardContent>
            {isLoading ? (
               <div className="h-[400px] w-full bg-muted/20 animate-pulse rounded-md" />
            ) : (
              <div className="h-[400px] w-full">
                <ResponsiveContainer width="100%" height="100%">
                  <BarChart data={summary?.ytdSavings} margin={{ top: 20, right: 30, left: 20, bottom: 5 }}>
                    <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} />
                    <XAxis dataKey="month" stroke="hsl(var(--muted-foreground))" />
                    <YAxis 
                      stroke="hsl(var(--muted-foreground))" 
                      tickFormatter={(val) => `₹${(val/1_00_000).toFixed(1)}L`}
                    />
                    <Tooltip 
                      contentStyle={{ backgroundColor: 'hsl(var(--card))', borderColor: 'hsl(var(--border))', borderRadius: '8px' }}
                      formatter={(val: number) => formatCurrency(val)}
                    />
                    <Legend />
                    <Bar dataKey="savings" name="Direct Savings" stackId="a" fill="hsl(var(--emerald-500))" fillOpacity={0.8} />
                    <Bar dataKey="fraud" name="Fraud Prevented" stackId="a" fill="hsl(var(--primary))" fillOpacity={0.8} />
                    <Bar dataKey="risk" name="Risk Mitigated" stackId="a" fill="hsl(var(--chart-2))" fillOpacity={0.8} radius={[4, 4, 0, 0]} />
                  </BarChart>
                </ResponsiveContainer>
              </div>
            )}
          </CardContent>
        </Card>

        <Card className="bg-card/50 backdrop-blur border-border/10">
          <CardHeader>
            <CardTitle>ROI Projection</CardTitle>
            <CardDescription>Estimated value over next 3 years</CardDescription>
          </CardHeader>
          <CardContent>
            <div className="space-y-6 mt-4">
              <div className="p-4 bg-muted/20 border border-border/20 rounded-lg">
                <div className="text-xs text-muted-foreground uppercase tracking-wider mb-1">Estimated ROI</div>
                <div className="text-4xl font-display font-bold text-primary">342%</div>
                <div className="text-sm mt-2 text-foreground/80">Payback period: <span className="font-bold">4.2 months</span></div>
              </div>

              <div className="space-y-3">
                <div className="flex justify-between items-center text-sm border-b border-border/10 pb-2">
                  <span className="text-muted-foreground">Year 1 Projection</span>
                  <span className="font-mono font-medium">₹35Cr</span>
                </div>
                <div className="flex justify-between items-center text-sm border-b border-border/10 pb-2">
                  <span className="text-muted-foreground">Year 2 Projection</span>
                  <span className="font-mono font-medium">₹48Cr</span>
                </div>
                <div className="flex justify-between items-center text-sm border-b border-border/10 pb-2">
                  <span className="text-muted-foreground">Year 3 Projection</span>
                  <span className="font-mono font-medium">₹59Cr</span>
                </div>
              </div>

              <Button className="w-full" variant="secondary">Adjust Parameters</Button>
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
